apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpcontent-rwx
  namespace: wordpress
spec:
  storageClassName: ""   # impede a default SC (ex.: local-path)
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-wordpress-wpcontent-rwx
