version: "3.8"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      PUID: 1001
      PGID: 1001
      TZ: Europe/Lisbon
    volumes:
      - /opt/sonarr:/config
      - /mnt/nas/media:/media
      - /mnt/nas/downloads:/downloads
    restart: unless-stopped
