services:
  postgres:
    image: postgres:15
    container_name: rundeck-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "rundeck"
      POSTGRES_USER: "rundeck"
      POSTGRES_PASSWORD: "rundeck"
      TZ: "Europe/Lisbon"
    volumes:
      - /opt/rundeck/rundeck-db-data:/var/lib/postgresql/data
      - /mnt/data:/opt/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rundeck -d rundeck -q || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  rundeck:
    image: rundeck/rundeck:5.16.0
    container_name: rundeck
    hostname: rundeck
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:4440"
    environment:
      RUNDECK_DATABASE_DRIVER: "org.postgresql.Driver"
      RUNDECK_DATABASE_URL: "jdbc:postgresql://postgres:5432/rundeck"
      RUNDECK_DATABASE_USERNAME: "rundeck"
      RUNDECK_DATABASE_PASSWORD: "rundeck"
      RUNDECK_GRAILS_URL: "https://rundeck.lbtec.org"
      RUNDECK_SERVER_FORWARDED: "true"
      RUNDECK_ADMIN_PASSWORD: "admin"
      RUNDECK_JETTY_HOST: "0.0.0.0"
      RUNDECK_JETTY_PORT: "4440"
      TZ: "Europe/Lisbon"
    user: "1000:0"
    volumes:
      - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key:ro
      - data:/home/rundeck/server/data
      - /opt/rundeck/configs:/home/rundeck/configs
      - /mnt/data:/opt/data

volumes:
  data:
