apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-rwx
  namespace: paperless
spec:
  storageClassName: ""            # <- impede herdar a default (local-path)
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-paperless-rwx     # <- liga explicitamente ao PV
