version: "3.8"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    environment:
      PUID: 1001
      PGID: 1001
      TZ: Europe/Lisbon
    volumes:
      - /opt/prowlarr:/config
      - /mnt/nas/downloads:/downloads
    restart: unless-stopped
