version: "3.8"

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      PUID: 1001
      PGID: 1001
      LOG_LEVEL: debug
      TZ: Europe/Lisbon
      PORT: 8004
    ports:
      - "8004:5055"
    volumes:
      - /opt/jellyseerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8004/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
