apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - redis.yaml
  - postgres.yaml
  - paperless.yaml
  - ingress.yaml
