apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-rwx
spec:
  storageClassName: ""            # <- explícito: sem StorageClass
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.55.100
    path: /paperless              # <-- ajusta se o teu path NFS for outro
  mountOptions:
    - nfsvers=4.1
    - rsize=262144
    - wsize=262144
    - hard
    - noatime
