services:
  terraform:
    image: hashicorp/terraform:1.13.0
    container_name: terraform
    working_dir: /workspace

    environment:
      TF_INPUT: "0"
      TF_IN_AUTOMATION: "1"
      TF_PLUGIN_CACHE_DIR: /terraform/plugin-cache
      TF_DATA_DIR: /terraform/data
      TF_CLI_CONFIG_FILE: /terraform/config/.terraformrc
    volumes:
      - /opt/terraform/workspace:/workspace
      - /opt/terraform/data:/terraform/data
      - opt/terraform/plugin-cache:/terraform/plugin-cache
      - /opt/terraform/config:/terraform/config
      - /mnt/data:/opt/data
    stdin_open: true
    tty: true
    command: ["version"]
    restart: "no"