apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-rwx
  namespace: media
spec:
  storageClassName: ""        # <-- adicionar
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-downloads-rwx
