apiVersion: v1
kind: Service
metadata:
  name: syncthing-direct
  namespace: syncthing
  labels:
    app.kubernetes.io/name: syncthing
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.60.152   # <- IP livre da pool do MetalLB
  selector:
    app.kubernetes.io/name: syncthing
  ports:
    - name: sync-tcp
      port: 22000
      targetPort: sync-tcp
      protocol: TCP
    - name: sync-udp
      port: 22000
      targetPort: sync-udp
      protocol: UDP
