apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-rwx
  namespace: syncthing
spec:
  storageClassName: ""           # <— impede herdar a default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-syncthing-rwx
