apiVersion: v1
kind: Service
metadata:
  name: stirlingpdf
  labels: { app.kubernetes.io/name: stirlingpdf }
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: stirlingpdf }
  ports:
    - name: http
      port: 80
      targetPort: http
