apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-rwx
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""              # torna explícito que é um PV estático
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.55.100
    path: /nextcloud
  mountOptions:
    - nfsvers=4.1
    - rsize=262144
    - wsize=262144
    - hard
    - noatime
