apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-rwx
  namespace: nextcloud
spec:
  storageClassName: ""         # não herda a default (local-path)
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi           # o valor aqui pode ser <= ao do PV
  volumeName: pv-nextcloud-rwx # liga explicitamente ao PV
